version: '2'
services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: maeeutovivo
    volumes:
      - ./blog/wp-newstrick:/var/www/html/wp-content/themes/wp-newstrick
    links:
      - db

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: maeeutovivo
    volumes:
      - ./mysql-data:/var/lib/mysql
