version: '2'
services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: maeeutovivo
    volumes:
      - ./blog/wp-content/themes:/var/www/html/wp-content/themes/
      - ./blog/wp-content/uploads:/var/www/html/wp-content/uploads/
    links:
      - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: maeeutovivo
    volumes:
      - ./mysql-data:/var/lib/mysql
